# Generated by Django 5.1.3 on 2024-11-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriwise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
