# Generated by Django 5.1.3 on 2024-12-01 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriwise', '0005_userprofile_food_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddiaryentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='image',
            field=models.ImageField(upload_to='food_images/'),
        ),
    ]
