# Generated by Django 5.1.3 on 2024-12-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriwise', '0007_alter_fooddiaryentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddiaryentry',
            name='user',
        ),
    ]
