# Generated by Django 5.1.3 on 2024-12-04 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriwise', '0010_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_id', models.CharField(max_length=100, unique=True)),
                ('food_name', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('nutrition_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('nutrition_details', models.JSONField(default=dict)),
                ('ingredients', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
