# Generated by Django 5.1.3 on 2024-12-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriwise', '0011_foodanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='api_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
