# Generated by Django 5.1.3 on 2024-12-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriwise', '0012_alter_fooddiaryentry_api_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='api_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
