# Generated by Django 5.1.4 on 2024-12-15 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriwise', '0013_alter_fooddiaryentry_api_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooddiaryentry',
            old_name='image',
            new_name='food_image',
        ),
        migrations.RenameField(
            model_name='fooddiaryentry',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='fooddiaryentry',
            name='api_response',
        ),
        migrations.RemoveField(
            model_name='fooddiaryentry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fooddiaryentry',
            name='title',
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='carbs',
            field=models.CharField(default=1.0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='cholesterol',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='fats',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='fiber',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='food_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='potassium',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='protein',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='sodium',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='sugar',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FoodAnalysis',
        ),
    ]
