# Generated by Django 5.1.4 on 2024-12-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriwise', '0014_rename_image_fooddiaryentry_food_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='cholesterol',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='fats',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='fiber',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='food_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='potassium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='sodium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='sugar',
            field=models.FloatField(),
        ),
    ]
