# Generated by Django 5.1.4 on 2024-12-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriwise', '0016_remove_userprofile_food_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='food_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_on_deficit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_on_exceed',
            field=models.BooleanField(default=False),
        ),
    ]
