# Generated by Django 3.2.25 on 2025-01-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calorie_goal',
            field=models.IntegerField(default=2000, verbose_name='Calorie Goal'),
        ),
    ]
