# Generated by Django 3.2.25 on 2025-01-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_calorie_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='carbs_goal',
            field=models.FloatField(default=300.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diet_type',
            field=models.CharField(choices=[('None', 'None'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Keto', 'Keto'), ('Paleo', 'Paleo')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fats_goal',
            field=models.FloatField(default=70.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_deficit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_exceed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='protein_goal',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='calorie_goal',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
